name: github pages release

on:
  push:
    branches:
      - main
      - baseline-branch
      - new-visual-branch
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Clean node_modules and cache
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm install

      - name: Build site
        env:
          CI: false
        run: |
          npm ci
          npm run build

      - name: Build storybook
        env:
          CI: false
        run: |
          npm run build.storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: www.saucedemo.com
