name: Meticulous

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
  statuses: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm

      - name: Clean Yarn Cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Serve project
        run: |
          yarn serve & 
          for i in {1..15}; do 
            if curl --output /dev/null --silent --head --fail "http://localhost:3000"; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 2
          done

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action/cloud-compute@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:3000/"
