name: Meticulous

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
  statuses: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Ensure Yarn is installed
        run: |
          npm install -g yarn

      - name: Clear Cache  # Point 6 added here
        run: rm -rf node_modules yarn.lock package-lock.json

      - name: Install dependencies
        run: |
          yarn install --force

      - name: Verify installation
        run: |
          yarn list @alwaysmeticulous/recorder-loader || echo "Dependency missing!"

      - name: Build project
        run: |
          yarn build

      - name: Serve project
        run: |
          yarn serve &
          sleep 5

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action/cloud-compute@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:3000/"
