on:
  push:
    branches:
      - main
      - baseline-branch  # Add baseline-branch if you need to trigger for that branch too
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
  statuses: read

jobs:
  test:
    name: Capture Visual Snapshots
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: yarn

      - name: Set NODE_OPTIONS for OpenSSL legacy provider
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --non-interactive

      - name: Build project
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn build

      - name: Start server in background
        run: |
          yarn global add serve
          serve -s build -l 3000 & echo $! > server.pid

      - name: Wait for server to be ready
        run: |
          for i in {1..12}; do  
            curl --silent --fail http://localhost:3000 && break
            echo "Waiting for server to be ready..."
            sleep 5
          done || (echo "Server failed to start!" && exit 1)

      - name: Install Meticulous CLI
        run: |
          yarn global add @alwaysmeticulous/cli
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Run Meticulous Visual Tests
        run: |
          meticulous run-all-tests \
            --apiToken=${{ secrets.METICULOUS_API_TOKEN }} \
            --appUrl="http://localhost:3000/" \
            --headless \
            --noSandbox \
            --baseTestRunId=Pkm7WCBcGMRzfgtTd7Mdc8rNNt
      - name: Stop server
        run: |
          kill $(cat server.pid) || true
