name: Meticulous

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
  statuses: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: yarn

      - name: Set NODE_OPTIONS
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        run: yarn install --non-interactive

      - name: Build project
        run: yarn build

      - name: Start server
        run: |
          yarn serve --host 0.0.0.0 &
          echo $! > server.pid  # Save the process ID
          sleep 30  # Ensure server is fully started

      - name: Verify server is running
        run: curl --retry 5 --retry-delay 5 --retry-connrefused -I http://localhost:3000

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action/cloud-compute@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:3000"

      - name: Stop server (Cleanup)
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true  # Kill the server process
            rm server.pid  # Remove the PID file
          fi
